import { NextRequest,NextResponse } from "next/server";
import { requireAdmin } from "@/lib/auth";
import { sql } from "@/lib/postgres";
export async function GET(req:NextRequest){const auth=await requireAdmin(req);if(auth.response)return auth.response;const p=req.nextUrl.searchParams,days=Math.min(365,Math.max(1,Number(p.get("days")||30))),key=p.get("key")||null,model=p.get("model")||null,params=[days,key,model];const where=`l.created_at>=now()-($1||' days')::interval and ($2::uuid is null or l.api_key_id=$2) and ($3::text is null or l.model=$3)`;const [summary,series,models,keys,users,failures,providers,recent]=await Promise.all([
 sql<any>(`select count(*)::int total,count(*) filter(where status<400)::int success,count(*) filter(where status>=400)::int errors,coalesce(avg(latency_ms),0)::int avg_latency_ms,coalesce(percentile_cont(.5) within group(order by latency_ms) filter(where latency_ms is not null),0)::int p50_latency_ms,coalesce(percentile_cont(.95) within group(order by latency_ms) filter(where latency_ms is not null),0)::int p95_latency_ms,coalesce(percentile_cont(.99) within group(order by latency_ms) filter(where latency_ms is not null),0)::int p99_latency_ms,coalesce(avg(provider_attempts),0)::numeric(8,2) avg_provider_attempts from usage_logs l where ${where}`,params),
 sql<any>(`select created_at::date date,count(*)::int count,count(*) filter(where status>=400)::int errors from usage_logs l where ${where} group by 1 order by 1`,params),
 sql<any>(`select coalesce(model,'unknown') model,count(*)::int count,coalesce(avg(latency_ms),0)::int avg_latency_ms from usage_logs l where ${where} group by 1 order by count desc limit 50`,params),
 sql<any>(`select l.api_key_id id,coalesce(k.name,'Untitled') name,coalesce(k.key_prefix,'') prefix,count(*)::int count from usage_logs l left join api_keys k on k.id=l.api_key_id where ${where} group by 1,2,3 order by count desc limit 50`,params),
 sql<any>(`select coalesce(u.username,'Unassigned') username,count(*)::int count from usage_logs l left join api_keys k on k.id=l.api_key_id left join users u on u.id=k.user_id where ${where} group by 1 order by count desc limit 50`,params),
 sql<any>(`select coalesce(failure_category,'unknown') category,count(*)::int count from usage_logs l where ${where} and status>=400 group by 1 order by count desc`,params),
 sql<any>(`select provider,count(*)::int count,count(*) filter(where status<400)::int success,count(*) filter(where status>=400)::int errors,coalesce(avg(latency_ms),0)::int avg_latency_ms,coalesce(percentile_cont(.95) within group(order by latency_ms) filter(where latency_ms is not null),0)::int p95_latency_ms,coalesce(avg(provider_attempts),0)::numeric(8,2) avg_attempts from usage_logs l where ${where} group by 1 order by count desc`,params),
 sql<any>(`select request_id,created_at,provider,model,status,latency_ms,provider_attempts,failure_category from usage_logs l where ${where} order by created_at desc limit 100`,params)
]);const s=summary[0]||{total:0,success:0,errors:0};return NextResponse.json({days,total:s.total,success:s.success,errors:s.errors,errorRate:s.total?s.errors/s.total:0,latency:{average:s.avg_latency_ms,p50:s.p50_latency_ms,p95:s.p95_latency_ms,p99:s.p99_latency_ms},averageProviderAttempts:Number(s.avg_provider_attempts||0),series,byModel:models,perKey:keys,perUser:users,failures,providers,recentRequests:recent});}
