import { NextRequest, NextResponse } from "next/server";
import { requireAdmin, audit } from "@/lib/auth";
import { sql, transaction } from "@/lib/postgres";
import { addCustomCredential, assertSafeProviderUrl, deleteCustomCredential, discoverCustomModels, setCustomCredentialActive, testCustomProvider, redactCustomCredential } from "@/lib/customProviders";

export async function GET(req:NextRequest){const a=await requireAdmin(req);if(a.response)return a.response;const providers=await sql<any>(`select p.*,count(distinct c.id)::int credentials,count(distinct m.id)::int models,count(distinct m.id) filter(where m.active)::int enabled_models from custom_providers p left join custom_provider_credentials c on c.provider_id=p.id left join custom_provider_models m on m.provider_id=p.id group by p.id order by p.created_at desc`),models=await sql<any>(`select id,provider_id,upstream_model_id,public_model_id,display_name,active,supports_streaming,last_seen_at,stale_at,disabled_reason from custom_provider_models order by public_model_id`),credentials=await sql<any>(`select id,provider_id,secret_prefix,active,priority,expires_at,parked_until,last_health_at,last_success_at,last_failure_at,last_failure_code,latency_ms,consecutive_failures,created_at from custom_provider_credentials order by provider_id,created_at desc`);return NextResponse.json({providers,models,credentials:credentials.map(redactCustomCredential)});}
export async function POST(req:NextRequest){const a=await requireAdmin(req);if(a.response)return a.response;const b=await req.json().catch(()=>({})),action=String(b.action||"create");try{if(action==="credential"){await addCustomCredential(String(b.provider_id||""),String(b.credential||""));await audit(a.user.id,"custom_provider.credential_replace","custom_provider",b.provider_id);return NextResponse.json({ok:true});}if(action==="test"){const result=await testCustomProvider(String(b.provider_id||""));await audit(a.user.id,"custom_provider.health_test","custom_provider",b.provider_id,{ok:true,latency_ms:result.latency_ms,models:result.models});return NextResponse.json(result);}if(action==="discover"){const count=await discoverCustomModels(String(b.provider_id||""));await audit(a.user.id,"custom_provider.discover","custom_provider",b.provider_id,{count});return NextResponse.json({ok:true,count});}const name=String(b.name||"").trim(),slug=String(b.slug||"").trim().toLowerCase(),url=await assertSafeProviderUrl(String(b.base_url||""));if(!name||!/^[-a-z0-9]{2,32}$/.test(slug))return NextResponse.json({error:"Valid name and slug are required."},{status:400});const base=url.href.replace(/\/$/,"");const row=(await sql<any>(`insert into custom_providers(name,slug,base_url,active) values($1,$2,$3,false) returning id,name,slug,base_url,active`,[name,slug,base]))[0];await audit(a.user.id,"custom_provider.create","custom_provider",row.id,{name,slug,base_url:base});return NextResponse.json({provider:row});}catch(e:any){return NextResponse.json({error:e.message},{status:400});}}
export async function PATCH(req:NextRequest){const a=await requireAdmin(req);if(a.response)return a.response;const b=await req.json().catch(()=>({}));try{if(b.action==="credential_unpark"){const rows=await sql<{id:string}>(`update custom_provider_credentials set parked_until=null,consecutive_failures=0 where id=$1 and provider_id=$2 returning id`,[String(b.credential_id||""),String(b.provider_id||"")]);await audit(a.user.id,"custom_provider.credential_unpark","custom_provider",b.provider_id,{credential_id:b.credential_id});return NextResponse.json({ok:rows.length===1});}if(b.action==="credential_priority"){const priority=Math.max(-1000,Math.min(1000,Number(b.priority)||0));const rows=await sql<{id:string}>(`update custom_provider_credentials set priority=$3 where id=$1 and provider_id=$2 returning id`,[String(b.credential_id||""),String(b.provider_id||""),priority]);await audit(a.user.id,"custom_provider.credential_priority","custom_provider",b.provider_id,{credential_id:b.credential_id,priority});return NextResponse.json({ok:rows.length===1});}if(Array.isArray(b.model_ids)){const ids=[...new Set(b.model_ids.map(String))].slice(0,500);if(!ids.length)return NextResponse.json({error:"Select at least one model."},{status:400});const rows=await sql<{id:string}>(`update custom_provider_models set active=$2 where provider_id=$1 and id=any($3::uuid[]) returning id`,[String(b.provider_id||""),Boolean(b.active),ids]);await audit(a.user.id,"custom_provider.models_bulk_update","custom_provider",b.provider_id,{active:Boolean(b.active),count:rows.length});return NextResponse.json({ok:true,updated:rows.length});}if(b.credential_id){const rows=await setCustomCredentialActive(String(b.provider_id),String(b.credential_id),Boolean(b.active));await audit(a.user.id,"custom_provider.credential_update","custom_provider",b.provider_id,{credential_id:b.credential_id,active:Boolean(b.active)});return NextResponse.json({ok:rows.length===1});}if(b.model_id){const rows=await sql(`update custom_provider_models set active=$2 where id=$1 returning id`,[b.model_id,Boolean(b.active)]);await audit(a.user.id,"custom_provider.model_update","custom_provider_model",b.model_id,{active:Boolean(b.active)});return NextResponse.json({ok:rows.length===1});}const rows=await sql(`update custom_providers set active=$2,updated_at=now() where id=$1 returning id`,[b.id,Boolean(b.active)]);await audit(a.user.id,"custom_provider.update","custom_provider",b.id,{active:Boolean(b.active)});return NextResponse.json({ok:rows.length===1});}catch(e:any){return NextResponse.json({error:e.message},{status:400});}}
export async function DELETE(req:NextRequest){
  const a=await requireAdmin(req);if(a.response)return a.response;
  const b=await req.json().catch(()=>({}));
  try{
    if(b.credential_id){const rows=await deleteCustomCredential(String(b.provider_id),String(b.credential_id));await audit(a.user.id,"custom_provider.credential_delete","custom_provider",b.provider_id,{credential_id:b.credential_id});return NextResponse.json({ok:rows.length===1});}
    const id=String(b.id||""),confirmation=String(b.confirmation||"").trim();
    if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id))return NextResponse.json({error:"A valid provider ID is required."},{status:400});
    const deleted=await transaction(async client=>{
      const provider=(await client.query<{id:string;name:string;slug:string}>(`select id,name,slug from custom_providers where id=$1 for update`,[id])).rows[0];
      if(!provider)return null;
      if(confirmation!==provider.slug)return {provider,confirmationFailed:true,jobs:0,models:0,credentials:0};
      const counts=(await client.query<{models:number;credentials:number}>(`select (select count(*)::int from custom_provider_models where provider_id=$1) models,(select count(*)::int from custom_provider_credentials where provider_id=$1) credentials`,[id])).rows[0];
      const jobs=await client.query(`update background_jobs set status='cancelled',locked_at=null,locked_by=null,updated_at=now(),last_error=null where type in ('custom_provider.health','custom_provider.discover') and payload->>'provider_id'=$1 and status in ('queued','running')`,[id]);
      await client.query(`delete from custom_providers where id=$1`,[id]);
      return {provider,confirmationFailed:false,jobs:jobs.rowCount||0,models:counts.models,credentials:counts.credentials};
    });
    if(!deleted)return NextResponse.json({error:"Custom provider not found."},{status:404});
    if(deleted.confirmationFailed)return NextResponse.json({error:"Type the provider slug to confirm deletion."},{status:409});
    await audit(a.user.id,"custom_provider.delete","custom_provider",id,{name:deleted.provider.name,slug:deleted.provider.slug,models_deleted:deleted.models,credentials_deleted:deleted.credentials,jobs_cancelled:deleted.jobs});
    return NextResponse.json({ok:true});
  }catch{return NextResponse.json({error:"Unable to delete custom provider."},{status:500});}
}
