"use client";
import { useEffect,useMemo,useState } from "react";
type Preset="chat"|"image"|"video"|"speech"; type Format="curl"|"javascript"|"python";
const presets:{id:Preset;label:string;path:string;body:any}[]=[{id:"chat",label:"Chat",path:"/v1/chat/completions",body:{model:"qwen3.8-max",messages:[{role:"user",content:"Explain why the sky is blue in two sentences."}],temperature:0.7,max_tokens:300,stream:false}},{id:"image",label:"Image",path:"/v1/images/generations",body:{model:"qwen-image-3.0",prompt:"A precise architectural ink drawing of a coastal observatory",size:"16:9"}},{id:"video",label:"Video",path:"/v1/videos/generations",body:{model:"qwen-wan",prompt:"Cloud shadows moving across a quiet desert",size:"16:9"}},{id:"speech",label:"Speech",path:"/v1/audio/speech",body:{input:"Hello from Syde.",voice:"Cherry"}}];
export function ApiExplorer({baseUrl}:{baseUrl:string}){
 const [preset,setPreset]=useState<Preset>("chat"),[key,setKey]=useState(""),[body,setBody]=useState(JSON.stringify(presets[0].body,null,2)),[models,setModels]=useState<string[]>([]),[result,setResult]=useState(""),[meta,setMeta]=useState(""),[busy,setBusy]=useState(false),[format,setFormat]=useState<Format>("curl");const selected=presets.find(x=>x.id===preset)!;
 useEffect(()=>{const timer=setTimeout(()=>fetch("/v1/models",{headers:key?{Authorization:`Bearer ${key}`}:{}}).then(r=>r.json()).then(j=>setModels((j.data||[]).map((x:any)=>x.id))).catch(()=>{}),250);return()=>clearTimeout(timer);},[key]);
 function choose(id:Preset){const p=presets.find(x=>x.id===id)!;setPreset(id);setBody(JSON.stringify(p.body,null,2));setResult("");setMeta("");}
 function setModel(model:string){try{const value=JSON.parse(body);value.model=model;setBody(JSON.stringify(value,null,2));}catch{}}
 const snippet=useMemo(()=>{const url=baseUrl+selected.path;if(format==="javascript")return `const response = await fetch(${JSON.stringify(url)}, {\n  method: "POST",\n  headers: { "Content-Type": "application/json", "Authorization": \`Bearer \${process.env.SYDE_API_KEY}\` },\n  body: JSON.stringify(${body})\n});\nconsole.log(await response.json());`;if(format==="python")return `import os, requests\n\nresponse = requests.post(${JSON.stringify(url)}, headers={\n    "Authorization": f"Bearer {os.environ['SYDE_API_KEY']}",\n    "Content-Type": "application/json",\n}, json=${body})\nprint(response.json())`;return `curl ${JSON.stringify(url)} \\\n  -H "Content-Type: application/json" \\\n  -H "Authorization: Bearer $SYDE_API_KEY" \\\n  -d ${JSON.stringify(body)}`;},[baseUrl,selected.path,body,format]);
 async function run(){setBusy(true);setResult("");setMeta("");const started=performance.now();try{const parsed=JSON.parse(body),r=await fetch(selected.path,{method:"POST",headers:{"Content-Type":"application/json",...(key?{Authorization:`Bearer ${key}`}:{})},body:JSON.stringify(parsed)}),requestId=r.headers.get("x-request-id")||"—",type=r.headers.get("content-type")||"";setMeta(`${r.status} · ${Math.round(performance.now()-started)} ms · ${requestId}`);if(type.includes("text/event-stream")&&r.body){const reader=r.body.getReader(),decoder=new TextDecoder();let text="";while(true){const {done,value}=await reader.read();if(done)break;text+=decoder.decode(value,{stream:true});setResult(text);}return;}if(type.includes("application/json"))setResult(JSON.stringify(await r.json(),null,2));else setResult(`[${type||"binary response"}] ${Number(r.headers.get("content-length")||0).toLocaleString()} bytes`);}catch(e:any){setResult(e.message);}finally{setBusy(false);}}
 return <section className="field py-14"><p className="eyebrow">Interactive reference</p><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><h2 className="h2 text-ink">Request laboratory</h2><p className="body mt-2 text-sm">Build a real request against this deployment. Credentials stay in memory and are never saved.</p></div><button className="btn btn-primary" disabled={busy} onClick={run}>{busy?"Running...":"Send request"}</button></div><div className="mt-6 flex flex-wrap gap-2">{presets.map(x=><button className={preset===x.id?"btn btn-primary":"btn btn-ghost"} key={x.id} onClick={()=>choose(x.id)}>{x.label}</button>)}</div><div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="border border-rule p-5"><label className="font-mono text-xs text-ink-3">API key (memory only)</label><input type="password" autoComplete="off" className="mt-2 w-full border border-rule bg-transparent px-3 py-2 font-mono text-xs text-ink outline-none focus:border-signal" value={key} onChange={e=>setKey(e.target.value)} placeholder="sk-..."/><div className="mt-4 grid gap-2 sm:grid-cols-[1fr_2fr]"><span className="self-center font-mono text-xs text-ink-3">{selected.path}</span>{preset==="chat"&&models.length>0&&<select className="border border-rule bg-transparent px-3 py-2 font-mono text-xs text-ink" value={(()=>{try{return JSON.parse(body).model||""}catch{return""}})()} onChange={e=>setModel(e.target.value)}><option value="">Choose discovered model</option>{models.map(model=><option key={model}>{model}</option>)}</select>}</div><textarea spellCheck={false} className="mt-3 min-h-72 w-full border border-rule bg-[var(--paper-2)] p-3 font-mono text-xs text-ink outline-none focus:border-signal" value={body} onChange={e=>setBody(e.target.value)}/></div><div className="border border-rule p-5"><div className="flex flex-wrap justify-between gap-3"><b className="text-sm text-ink">Response</b><span className="font-mono text-xs text-ink-3">{meta}</span></div><pre className="mt-3 min-h-72 max-h-[32rem] overflow-auto whitespace-pre-wrap break-words bg-[var(--paper-2)] p-3 text-xs text-ink-2" aria-live="polite">{result||"The response body will appear here."}</pre></div></div><details className="mt-4 border border-rule p-5"><summary className="cursor-pointer text-sm text-ink">Generated request</summary><div className="mt-4 flex gap-2">{(["curl","javascript","python"] as Format[]).map(x=><button key={x} className={format===x?"btn btn-primary":"btn btn-ghost"} onClick={()=>setFormat(x)}>{x}</button>)}</div><pre className="mt-3 overflow-auto whitespace-pre-wrap bg-[var(--paper-2)] p-3 text-xs text-ink-2">{snippet}</pre></details></section>;
}
