import { sql } from "./postgres";
import { decryptCredential, encryptCredential } from "./credentialEncryption";
import { assertSafeProviderUrl, providerFetch } from "./providerUrl";
import { getSetting } from "./settings";

const MAX_JSON_BYTES = 10 * 1024 * 1024;
const ADMIN_CREDENTIAL_FIELDS = ["id", "provider_id", "secret_prefix", "active", "priority", "expires_at", "parked_until", "last_health_at", "last_success_at", "last_failure_at", "last_failure_code", "latency_ms", "consecutive_failures", "created_at"] as const;
export function redactCustomCredential(row: Record<string, unknown>) {
  return Object.fromEntries(ADMIN_CREDENTIAL_FIELDS.filter((field) => field in row).map((field) => [field, row[field]]));
}
export type CustomModel = { id:string; provider_id:string; upstream_model_id:string; provider_slug:string; provider_name:string; supports_streaming:boolean; base_url:string; chat_path:string; request_timeout_ms:number };
export class CustomProviderError extends Error { constructor(message:string, public status=502, public category="provider_error", public attempts=1) { super(message); } }

export async function customProviderCapacity() {
  const rows = await sql<{providers:number;models:number;credentials:number;parked:number}>(`select count(distinct p.id)::int providers,count(distinct m.id)::int models,count(distinct c.id) filter(where c.active and (c.expires_at is null or c.expires_at>now()) and (c.parked_until is null or c.parked_until<=now()))::int credentials,count(distinct c.id) filter(where c.active and c.parked_until>now())::int parked from custom_providers p left join custom_provider_models m on m.provider_id=p.id and m.active left join custom_provider_credentials c on c.provider_id=p.id where p.active`);
  return rows[0] || { providers:0, models:0, credentials:0, parked:0 };
}
export async function listCustomModels() { return sql<any>(`select m.public_model_id id,m.provider_id,m.upstream_model_id,p.slug provider_slug,p.name provider_name,m.supports_streaming,p.base_url,p.chat_path,p.request_timeout_ms from custom_provider_models m join custom_providers p on p.id=m.provider_id where p.active and m.active order by m.public_model_id`); }
export async function customModel(id:string):Promise<CustomModel|null> { return (await sql<CustomModel>(`select m.public_model_id id,m.provider_id,m.upstream_model_id,p.slug provider_slug,p.name provider_name,m.supports_streaming,p.base_url,p.chat_path,p.request_timeout_ms from custom_provider_models m join custom_providers p on p.id=m.provider_id where p.active and m.active and m.public_model_id=$1`,[id]))[0]||null; }

async function limitedJson(response:Response) {
  const declared = Number(response.headers.get("content-length") || 0);
  if (declared > MAX_JSON_BYTES) throw new CustomProviderError("Provider response is too large.", 502, "response_too_large");
  const reader = response.body?.getReader();
  if (!reader) throw new CustomProviderError("Provider returned an empty response.", 502, "invalid_response");
  const chunks:Uint8Array[]=[]; let total=0;
  while (true) { const {done,value}=await reader.read(); if(done)break; total+=value.byteLength; if(total>MAX_JSON_BYTES){await reader.cancel();throw new CustomProviderError("Provider response is too large.",502,"response_too_large");} chunks.push(value); }
  const bytes=new Uint8Array(total); let offset=0; for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}
  try { return JSON.parse(new TextDecoder().decode(bytes)); } catch { throw new CustomProviderError("Provider returned invalid JSON.",502,"invalid_response"); }
}
function contentType(response:Response){return (response.headers.get("content-type")||"").toLowerCase();}
function failure(status:number){if(status===401||status===403)return "authentication_error";if(status===429)return "rate_limited";if(status>=500)return "provider_server_error";return "provider_client_error";}
async function markFailure(id:string,status:number,category:string){const park=category==="rate_limited"?"5 minutes":category==="authentication_error"?"30 minutes":status>=500?"1 minute":null;await sql(`update custom_provider_credentials set consecutive_failures=consecutive_failures+1,last_failure_at=now(),last_failure_code=$2,parked_until=case when $3::text is null then parked_until else now()+$3::interval end where id=$1`,[id,category,park]);}
async function markSuccess(id:string,latency:number){await sql(`update custom_provider_credentials set consecutive_failures=0,last_success_at=now(),last_health_at=now(),last_failure_code=null,parked_until=null,latency_ms=$2 where id=$1`,[id,latency]);}

export async function testCustomProvider(providerId:string){const p=(await sql<any>(`select * from custom_providers where id=$1`,[providerId]))[0];if(!p)throw new Error("Provider not found.");const c=(await sql<any>(`select * from claim_custom_provider_credential($1,'{}'::uuid[])`,[providerId]))[0];if(!c)throw new Error("No usable provider credential.");const started=Date.now();try{const response=await providerFetch(p.base_url,p.models_path,{headers:{authorization:`Bearer ${decryptCredential(c.secret_ciphertext)}`},signal:AbortSignal.timeout(p.request_timeout_ms)});if(!response.ok){const category=failure(response.status);await markFailure(c.id,response.status,category);throw new Error(`Provider health check failed with HTTP ${response.status}.`);}if(!contentType(response).includes("application/json")){await markFailure(c.id,502,"invalid_response");throw new Error("Provider health check did not return JSON.");}const json:any=await limitedJson(response);if(!Array.isArray(json.data)){await markFailure(c.id,502,"invalid_response");throw new Error("Provider health response has an invalid model list.");}const latency=Date.now()-started;await markSuccess(c.id,latency);return {ok:true,latency_ms:latency,models:json.data.length,credential_prefix:c.secret_prefix};}catch(error){if(error instanceof Error&&error.message.startsWith("Provider health"))throw error;await markFailure(c.id,502,error instanceof DOMException&&error.name==="TimeoutError"?"timeout":"network_error");throw error;}}

export function normalizePublicModelName(id:string){return id.toLowerCase().replace(/[^a-z0-9._-]+/g,"-").replace(/-+/g,"-").replace(/^[._-]+|[._-]+$/g,"").slice(0,128)||"model";}
async function availablePublicModelName(providerId:string,upstreamId:string){const base=normalizePublicModelName(upstreamId);for(let suffix=1;suffix<10000;suffix++){const tail=suffix===1?"":`-${suffix}`,candidate=`${base.slice(0,128-tail.length)}${tail}`;if(!(await sql(`select 1 from custom_provider_models where provider_id=$1 and lower(public_name)=lower($2)`,[providerId,candidate])).length)return candidate;}throw new Error("Could not allocate a unique public model name.");}
export async function discoverCustomModels(providerId:string){const p=(await sql<any>(`select * from custom_providers where id=$1`,[providerId]))[0];if(!p)throw new Error("Provider not found.");const c=(await sql<any>(`select * from claim_custom_provider_credential($1,'{}'::uuid[])`,[providerId]))[0];if(!c)throw new Error("No usable provider credential.");const started=Date.now();const response=await providerFetch(p.base_url,p.models_path,{headers:{authorization:`Bearer ${decryptCredential(c.secret_ciphertext)}`},signal:AbortSignal.timeout(p.request_timeout_ms)});if(!response.ok){const category=failure(response.status);await markFailure(c.id,response.status,category);throw new Error(`Model discovery failed with HTTP ${response.status}.`);}if(!contentType(response).includes("application/json")){await markFailure(c.id,502,"invalid_response");throw new Error("Model discovery did not return JSON.");}const json:any=await limitedJson(response);const models=Array.isArray(json.data)?json.data:[];const seen:string[]=[];for(const item of models){if(typeof item?.id!=="string"||!item.id||item.id.length>200)continue;seen.push(item.id);const existing=await sql<{public_name:string}>(`select public_name from custom_provider_models where provider_id=$1 and upstream_model_id=$2`,[providerId,item.id]);const publicName=existing[0]?.public_name||await availablePublicModelName(providerId,item.id);await sql(`insert into custom_provider_models(provider_id,upstream_model_id,public_name,public_model_id,display_name,last_seen_at) values($1,$2,$3,$4,$5,now()) on conflict(provider_id,upstream_model_id) do update set display_name=excluded.display_name,last_seen_at=now(),stale_at=null,disabled_reason=case when custom_provider_models.disabled_reason='missing_upstream' then null else custom_provider_models.disabled_reason end`,[providerId,item.id,publicName,`${p.slug}/${publicName}`,String(item.name||item.id).slice(0,200)]);}await sql(`update custom_provider_models set stale_at=coalesce(stale_at,now()) where provider_id=$1 and not(upstream_model_id=any($2::text[]))`,[providerId,seen]);const { stale_grace_hours }=await getSetting("custom_providers");await sql(`update custom_provider_models set active=false,disabled_reason='missing_upstream' where provider_id=$1 and stale_at<=now()-($2 * interval '1 hour') and active`,[providerId,stale_grace_hours]);await markSuccess(c.id,Date.now()-started);return seen.length;}
export async function addCustomCredential(providerId:string,secret:string){const clean=secret.trim();if(!clean||clean.length>4096)throw new Error("Credential is required and must be at most 4096 characters.");await sql(`update custom_provider_credentials set active=false where provider_id=$1 and active`,[providerId]);return sql(`insert into custom_provider_credentials(provider_id,secret_ciphertext,secret_prefix) values($1,$2,$3) returning id`,[providerId,encryptCredential(clean),`${clean.slice(0,6)}...`]);}
export async function setCustomCredentialActive(providerId:string,credentialId:string,active:boolean){return sql(`update custom_provider_credentials set active=$3 where id=$1 and provider_id=$2 returning id`,[credentialId,providerId,active]);}
export async function deleteCustomCredential(providerId:string,credentialId:string){return sql(`delete from custom_provider_credentials where id=$1 and provider_id=$2 returning id`,[credentialId,providerId]);}

export interface CustomProviderProxyDependencies {
  claimCredential(providerId: string, excluded: string[]): Promise<any | null>;
  fetch(base: string, path: string, init: RequestInit): Promise<Response>;
  decrypt(ciphertext: string): string;
  markFailure(id: string, status: number, category: string): Promise<void>;
  markSuccess(id: string, latency: number): Promise<void>;
}

const defaultProxyDependencies: CustomProviderProxyDependencies = {
  async claimCredential(providerId, excluded) { return (await sql<any>(`select * from claim_custom_provider_credential($1,$2::uuid[])`, [providerId, excluded]))[0] || null; },
  fetch: providerFetch,
  decrypt: decryptCredential,
  markFailure,
  markSuccess,
};

export async function proxyCustomChat(model:CustomModel,body:any,signal:AbortSignal,deps:CustomProviderProxyDependencies=defaultProxyDependencies){const excluded:string[]=[];for(let attempt=1;attempt<=3;attempt++){const c=await deps.claimCredential(model.provider_id,excluded);if(!c)throw new CustomProviderError("Custom provider capacity exhausted.",503,"provider_capacity_exhausted",attempt-1);excluded.push(c.id);const started=Date.now();try{const response=await deps.fetch(model.base_url,model.chat_path,{method:"POST",headers:{authorization:`Bearer ${deps.decrypt(c.secret_ciphertext)}`,"content-type":"application/json","accept":body.stream?"text/event-stream":"application/json"},body:JSON.stringify({...body,model:model.upstream_model_id}),signal:AbortSignal.any([signal,AbortSignal.timeout(model.request_timeout_ms)])});if(!response.ok){const category=failure(response.status);await deps.markFailure(c.id,response.status,category);if(response.status===429||response.status>=500)continue;throw new CustomProviderError(`Provider rejected the request with HTTP ${response.status}.`,response.status,category,attempt);}const expected=body.stream?"text/event-stream":"application/json";if(!contentType(response).includes(expected)){await deps.markFailure(c.id,502,"invalid_response");throw new CustomProviderError("Provider returned an unexpected content type.",502,"invalid_response",attempt);}if(!body.stream){const json:any=await limitedJson(response);if(!json||!Array.isArray(json.choices))throw new CustomProviderError("Provider returned an invalid chat response.",502,"invalid_response",attempt);await deps.markSuccess(c.id,Date.now()-started);return{response:new Response(JSON.stringify(json),{status:response.status,headers:{"content-type":"application/json"}}),attempts:attempt,credentialId:c.id,started};}await deps.markSuccess(c.id,Date.now()-started);return{response,attempts:attempt,credentialId:c.id,started};}catch(e){if(e instanceof CustomProviderError)throw e;await deps.markFailure(c.id,502,e instanceof DOMException&&e.name==="TimeoutError"?"timeout":"network_error");const cause=e instanceof Error?e.message:"unknown";if(attempt===3||excluded.length===1)throw new CustomProviderError(`Custom provider network request failed: ${cause}`,502,"network_error",attempt);}}throw new CustomProviderError("Custom provider unavailable.",503,"provider_capacity_exhausted",3);}
export { assertSafeProviderUrl };
